FROM lapidarioz/python3-opencv4-dlib-cuda:latest

ENV API_PORT=5000

EXPOSE ${API_PORT}

WORKDIR /tmp
COPY requirements.txt.api /tmp
RUN pip install --no-cache-dir -r requirements.txt.api

WORKDIR /data
COPY data .

WORKDIR /app
COPY app.py /app
COPY api.py /app

CMD [ "python", "./api.py" ]
