FROM lapidarioz/python3-opencv4-dlib-cuda:latest

VOLUME /data

WORKDIR /tmp
COPY requirements.txt.api /tmp
RUN pip install --no-cache-dir -r requirements.txt.api

WORKDIR /app
COPY app.py /app
COPY cli.py /app

ENTRYPOINT [ "python", "./cli.py" ]
